name: HelloFlow
options:
  bundleIdPrefix: com.flow
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.flow.hello
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ""
    INFOPLIST_KEY_CFBundleDisplayName: Hello
targets:
  HelloFlow:
    type: application
    platform: iOS
    sources:
      - path: MessengerApp
    settings:
      base:
        PRODUCT_NAME: Hello
        INFOPLIST_KEY_CFBundleDisplayName: Hello
